from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
PRODUCTS_DIR = ROOT / "products"

IMAGE_POOL = [
    "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1526045612212-70caf35c14df?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80",
]

CATEGORY_CATALOG = {
    "Aanbiedingen": {
        "folder": "aanbiedingen",
        "products": [
            {"name": "TrendMix Gaming Combo", "price": 699.00, "old_price": 899.00, "brand": "TrendMix", "badge": "Hot"},
            {"name": "Smart Home Starter Pack", "price": 179.00, "old_price": 249.00, "brand": "TrendMix", "badge": "Deal"},
            {"name": "Aurora RGB Desk Set", "price": 149.00, "old_price": 219.00, "brand": "TrendMix", "badge": "New"},
            {"name": "Clean Beauty Kit", "price": 89.00, "old_price": 119.00, "brand": "TrendMix", "badge": "Promo"},
            {"name": "Performance Gaming Kit", "price": 1299.00, "old_price": 1599.00, "brand": "TrendMix", "badge": "Best"},
            {"name": "Desk Flex Bundle", "price": 199.00, "old_price": 269.00, "brand": "TrendMix", "badge": "Hot"},
            {"name": "Wellness Recovery Pack", "price": 159.00, "old_price": 219.00, "brand": "TrendMix", "badge": "Top"},
            {"name": "Lifestyle Essentials", "price": 119.00, "old_price": 169.00, "brand": "TrendMix", "badge": "Deal"},
            {"name": "Mini Projector Bundle", "price": 249.00, "old_price": 329.00, "brand": "TrendMix", "badge": "New"},
            {"name": "Fitness Setup Pro", "price": 229.00, "old_price": 299.00, "brand": "TrendMix", "badge": "Hot"},
            {"name": "Beauty Care Week", "price": 79.00, "old_price": 109.00, "brand": "TrendMix", "badge": "Promo"},
            {"name": "RGB Air Flow Kit", "price": 109.00, "old_price": 159.00, "brand": "TrendMix", "badge": "Deal"},
            {"name": "Portable Work Station", "price": 349.00, "old_price": 449.00, "brand": "TrendMix", "badge": "Best"},
            {"name": "Smart Lock & Sensor", "price": 219.00, "old_price": 289.00, "brand": "TrendMix", "badge": "New"},
            {"name": "Recovery Massage Set", "price": 69.00, "old_price": 99.00, "brand": "TrendMix", "badge": "Hot"},
            {"name": "RGB Strip Lighting", "price": 59.00, "old_price": 81.00, "brand": "TrendMix", "badge": "Deal"},
            {"name": "Travel Tech Organizer", "price": 45.00, "old_price": 69.00, "brand": "TrendMix", "badge": "Top"},
            {"name": "Wearable Wellness Kit", "price": 189.00, "old_price": 249.00, "brand": "TrendMix", "badge": "New"},
            {"name": "Quiet Comfort Pack", "price": 139.00, "old_price": 179.00, "brand": "TrendMix", "badge": "Promo"},
            {"name": "Performance Accessory Pack", "price": 119.00, "old_price": 159.00, "brand": "TrendMix", "badge": "Hot"},
        ],
    },
    "Beauty & Care": {
        "folder": "beauty-care",
        "products": [
            {"name": "LED gezichtsmasker", "price": 34.95, "brand": "GlowLab", "badge": "Top"},
            {"name": "Facial cleansing brush", "price": 29.95, "brand": "GlowLab", "badge": "Bestseller"},
            {"name": "Ice facial roller", "price": 22.95, "brand": "GlowLab", "badge": "Fresh"},
            {"name": "Gua Sha set", "price": 27.95, "brand": "GlowLab", "badge": "Trend"},
            {"name": "Microcurrent facial device", "price": 149.00, "brand": "GlowLab", "badge": "Premium"},
            {"name": "Elektrische gezichtstrimmer", "price": 39.95, "brand": "GlowLab", "badge": "Hot"},
            {"name": "Makeup organizer", "price": 32.95, "brand": "GlowLab", "badge": "New"},
            {"name": "Make-up tas", "price": 41.95, "brand": "GlowLab", "badge": "Travel"},
            {"name": "Reusable makeup remover pads", "price": 18.95, "brand": "GlowLab", "badge": "Eco"},
            {"name": "Lip balm", "price": 12.95, "brand": "GlowLab", "badge": "Daily"},
            {"name": "Acne patches", "price": 16.95, "brand": "GlowLab", "badge": "Care"},
            {"name": "Moisturizer", "price": 24.95, "brand": "GlowLab", "badge": "Hydrate"},
            {"name": "Face serum", "price": 39.95, "brand": "GlowLab", "badge": "Glow"},
            {"name": "Hair oil", "price": 26.95, "brand": "GlowLab", "badge": "Repair"},
            {"name": "Scalp massager", "price": 31.95, "brand": "GlowLab", "badge": "Wellness"},
            {"name": "Heatless curling set", "price": 36.95, "brand": "GlowLab", "badge": "Style"},
            {"name": "Elektrische hoofdhuidborstel", "price": 42.95, "brand": "GlowLab", "badge": "Premium"},
            {"name": "Nagel-/manicurekit", "price": 26.95, "brand": "GlowLab", "badge": "Care"},
            {"name": "Press-on nails", "price": 19.95, "brand": "GlowLab", "badge": "Trend"},
            {"name": "Massage gun", "price": 89.95, "brand": "GlowLab", "badge": "Recovery"},
        ],
    },
    "Gadgets": {
        "folder": "gadgets",
        "products": [
            {"name": "Smart LED lamp", "price": 29.95, "brand": "TechWave", "badge": "Smart"},
            {"name": "Mini Bluetooth speaker", "price": 39.95, "brand": "TechWave", "badge": "Audio"},
            {"name": "Wireless charging pad", "price": 34.95, "brand": "TechWave", "badge": "Charge"},
            {"name": "Smart key finder", "price": 24.95, "brand": "TechWave", "badge": "Mini"},
            {"name": "Portable phone stand", "price": 18.95, "brand": "TechWave", "badge": "Desk"},
            {"name": "USB rechargeable fan", "price": 21.95, "brand": "TechWave", "badge": "Travel"},
            {"name": "LED desk light", "price": 26.95, "brand": "TechWave", "badge": "Light"},
            {"name": "Wireless presenter", "price": 44.95, "brand": "TechWave", "badge": "Office"},
            {"name": "Phone camera lens kit", "price": 49.95, "brand": "TechWave", "badge": "Creator"},
            {"name": "Portable power bank", "price": 54.95, "brand": "TechWave", "badge": "Power"},
            {"name": "Bluetooth tracker", "price": 22.95, "brand": "TechWave", "badge": "Tracker"},
            {"name": "Smart night light", "price": 27.95, "brand": "TechWave", "badge": "Mood"},
            {"name": "Foldable phone holder", "price": 17.95, "brand": "TechWave", "badge": "Travel"},
            {"name": "USB-C cable organizer", "price": 14.95, "brand": "TechWave", "badge": "Cable"},
            {"name": "Mini projector", "price": 189.00, "brand": "TechWave", "badge": "Cinema"},
            {"name": "Wireless keyboard", "price": 59.95, "brand": "TechWave", "badge": "Office"},
            {"name": "Wireless mouse", "price": 42.95, "brand": "TechWave", "badge": "Desk"},
            {"name": "Desktop phone dock", "price": 28.95, "brand": "TechWave", "badge": "Desk"},
            {"name": "LED ambient light", "price": 31.95, "brand": "TechWave", "badge": "Mood"},
            {"name": "Travel tech organizer", "price": 24.95, "brand": "TechWave", "badge": "Travel"},
        ],
    },
    "Lifestyle & Sport": {
        "folder": "lifestyle-sport",
        "products": [
            {"name": "Smart fitness tracker", "price": 79.95, "brand": "MoveFit", "badge": "Fit"},
            {"name": "Resistance bands set", "price": 24.95, "brand": "MoveFit", "badge": "Workout"},
            {"name": "Adjustable dumbbell", "price": 49.95, "brand": "MoveFit", "badge": "Gym"},
            {"name": "Yoga mat", "price": 29.95, "brand": "MoveFit", "badge": "Wellness"},
            {"name": "Sports water bottle", "price": 19.95, "brand": "MoveFit", "badge": "Hydrate"},
            {"name": "Running waist bag", "price": 22.95, "brand": "MoveFit", "badge": "Run"},
            {"name": "Massage ball set", "price": 24.95, "brand": "MoveFit", "badge": "Recovery"},
            {"name": "Foam roller", "price": 34.95, "brand": "MoveFit", "badge": "Recovery"},
            {"name": "Gym training gloves", "price": 22.95, "brand": "MoveFit", "badge": "Lift"},
            {"name": "Portable Bluetooth speaker", "price": 39.95, "brand": "MoveFit", "badge": "Audio"},
            {"name": "RVS tumbler", "price": 26.95, "brand": "MoveFit", "badge": "Lifestyle"},
            {"name": "Herbruikbare waterfles", "price": 23.95, "brand": "MoveFit", "badge": "Daily"},
            {"name": "E-reader hoes", "price": 17.95, "brand": "MoveFit", "badge": "Read"},
            {"name": "Mini projector", "price": 189.00, "brand": "MoveFit", "badge": "Home"},
            {"name": "Draadloze earbuds", "price": 69.95, "brand": "MoveFit", "badge": "Audio"},
            {"name": "Travel organizer", "price": 29.95, "brand": "MoveFit", "badge": "Travel"},
            {"name": "Laptop stand", "price": 39.95, "brand": "MoveFit", "badge": "Desk"},
            {"name": "Minimalistische bureaulamp", "price": 46.95, "brand": "MoveFit", "badge": "Desk"},
            {"name": "Aroma diffuser", "price": 41.95, "brand": "MoveFit", "badge": "Relax"},
            {"name": "Portable power station", "price": 199.00, "brand": "MoveFit", "badge": "Power"},
        ],
    },
    "PC-Componenten": {
        "folder": "pc-componenten",
        "products": [
            {"name": "32GB DDR5", "price": 149.95, "brand": "NexaCore", "badge": "Popular"},
            {"name": "2TB NVMe", "price": 129.95, "brand": "NexaCore", "badge": "Fast"},
            {"name": "Gaming muis", "price": 59.95, "brand": "NexaCore", "badge": "Gaming"},
            {"name": "Mechanisch toetsenbord", "price": 119.95, "brand": "NexaCore", "badge": "Gaming"},
            {"name": "Gaming headset", "price": 89.95, "brand": "NexaCore", "badge": "Audio"},
            {"name": "850W Gold PSU", "price": 149.95, "brand": "NexaCore", "badge": "Power"},
            {"name": "240mm AIO", "price": 129.95, "brand": "NexaCore", "badge": "Cooling"},
            {"name": "ARGB fans", "price": 49.95, "brand": "NexaCore", "badge": "Cooling"},
            {"name": "64GB DDR5", "price": 299.95, "brand": "NexaCore", "badge": "Elite"},
            {"name": "4TB NVMe", "price": 249.95, "brand": "NexaCore", "badge": "Storage"},
            {"name": "1000W Gold PSU", "price": 199.95, "brand": "NexaCore", "badge": "Power"},
            {"name": "360mm AIO", "price": 189.95, "brand": "NexaCore", "badge": "Cooling"},
            {"name": "Ryzen X3D", "price": 489.95, "brand": "NexaCore", "badge": "Gaming"},
            {"name": "B850 moederbord", "price": 249.95, "brand": "NexaCore", "badge": "Mainboard"},
            {"name": "X870 moederbord", "price": 319.95, "brand": "NexaCore", "badge": "Premium"},
            {"name": "1200W Platinum PSU", "price": 279.95, "brand": "NexaCore", "badge": "Premium"},
            {"name": "PCIe 5 SSD", "price": 279.95, "brand": "NexaCore", "badge": "Next"},
            {"name": "420mm AIO", "price": 229.95, "brand": "NexaCore", "badge": "Elite"},
            {"name": "GPU support bracket", "price": 39.95, "brand": "NexaCore", "badge": "Accessory"},
            {"name": "Premium PSU cables", "price": 54.95, "brand": "NexaCore", "badge": "Upgrade"},
        ],
    },
    "Smart Home": {
        "folder": "smart-home",
        "products": [
            {"name": "Smart LED light bulb", "price": 24.95, "brand": "HomeNest", "badge": "Smart"},
            {"name": "WiFi smart plug", "price": 22.95, "brand": "HomeNest", "badge": "Smart"},
            {"name": "Smart motion sensor", "price": 34.95, "brand": "HomeNest", "badge": "Security"},
            {"name": "Smart door sensor", "price": 24.95, "brand": "HomeNest", "badge": "Security"},
            {"name": "RGB LED light strip", "price": 29.95, "brand": "HomeNest", "badge": "Mood"},
            {"name": "Smart night light", "price": 19.95, "brand": "HomeNest", "badge": "Ambience"},
            {"name": "Smart temperature sensor", "price": 32.95, "brand": "HomeNest", "badge": "Climate"},
            {"name": "Smart alarm sensor", "price": 34.95, "brand": "HomeNest", "badge": "Security"},
            {"name": "Smart remote controller", "price": 27.95, "brand": "HomeNest", "badge": "Control"},
            {"name": "WiFi security camera", "price": 69.95, "brand": "HomeNest", "badge": "Camera"},
            {"name": "Smart light switch", "price": 39.95, "brand": "HomeNest", "badge": "Home"},
            {"name": "Smart plug with energy monitor", "price": 34.95, "brand": "HomeNest", "badge": "Eco"},
            {"name": "Smart clock", "price": 44.95, "brand": "HomeNest", "badge": "Smart"},
            {"name": "Smart air quality monitor", "price": 54.95, "brand": "HomeNest", "badge": "Air"},
            {"name": "Smart water leak sensor", "price": 29.95, "brand": "HomeNest", "badge": "Safety"},
            {"name": "Smart doorbell", "price": 99.95, "brand": "HomeNest", "badge": "Security"},
            {"name": "Smart LED desk lamp", "price": 42.95, "brand": "HomeNest", "badge": "Desk"},
            {"name": "Smart power strip", "price": 49.95, "brand": "HomeNest", "badge": "Power"},
            {"name": "Smart curtain controller", "price": 59.95, "brand": "HomeNest", "badge": "Automation"},
            {"name": "Smart home starter kit", "price": 119.95, "brand": "HomeNest", "badge": "Bundle"},
        ],
    },
}

for category_name, config in CATEGORY_CATALOG.items():
    folder = PRODUCTS_DIR / config["folder"]
    folder.mkdir(parents=True, exist_ok=True)
    products = []

    for index, product in enumerate(config["products"], start=1):
        price = float(product["price"])
        cost = round(price * 0.48, 2)
        old_price = product.get("old_price", round(price * 1.25, 2))
        item = {
            "name": product["name"],
            "price": price,
            "cost_price": cost,
            "margin": round(((price - cost) / price) * 100, 1),
            "brand": product.get("brand", "TrendMix"),
            "image": IMAGE_POOL[(index - 1) % len(IMAGE_POOL)],
            "image_url": IMAGE_POOL[(index - 1) % len(IMAGE_POOL)],
            "old_price": old_price,
            "description": f"{product['name']} van {product.get('brand', 'TrendMix')} – perfect voor {category_name.lower()} en dagelijks gebruik.",
            "rating": 4.7 + (index % 3) * 0.1,
            "reviews": 110 + index * 14,
            "affiliate_url": "#",
            "affiliate_network": "TrendMix",
            "badge": product.get("badge", "Trend"),
            "is_offer": 1 if old_price else 0,
            "supplier": "TrendMix Supplier",
            "orders": 0,
            "category": category_name,
        }
        products.append(item)

    payload = {"category": category_name, "products": products}
    (folder / "products.json").write_text(json.dumps(payload, ensure_ascii=False, indent=4), encoding="utf-8")

print(f"Updated product catalog for {len(CATEGORY_CATALOG)} categories.")
